### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by Svenmax** [hogelog/whispercppapp#4]
Thank you for developing such a great software. I have some suggestions ;
1. Supporting placing models in the software directory,All operations are performed in the software, which is more convenient.
**Skip download File: 'C:\Users\ADMINI~1\AppData\Local\Temp\org.hogel.whispercppapp\app\ggml-large.bin'
$ .\data/flutter_assets/exe\ffmpeg -i D:\whisper\1.mp3 -ar 16000 -ac 1 -c:a pcm_s16le C:\Users\ADMINI~1\AppData\Local\Temp\org.hogel.whispercppapp\input.wav**

2.Add an input box that can manually add parameters

**Comment by bilalazhar72** [comment]
@Svenmax  i guess they are not developing this anymore

**Comment by hogelog** [comment]
@Svenmax 
Thanks for the suggestion, but I am developing whispercppapp as a simplified tool for beginning computer students who can't handle the CLI whipper.cpp.

If you want to use it in a more advanced way, please use whisper.cpp directly, or use or develop other front-end tools.
(Of course, you are welcome to fork this whispercppapp and develop your own)
